In [113]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

import warnings
warnings.filterwarnings('ignore')

In [114]:
#read data from input csv file
bostonhouse_data = pd.read_csv("regressionDataSet/boston_housing.csv")
bostonhouse_data.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,5.33,36.2

In [115]:
#fetching all the columns and datatypes involved
bostonhouse_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    int64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    int64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(11), int64(3)
memory usage: 55.5 KB

### Selecting features to work on

In [116]:
bostonHouse_df=bostonhouse_data[['RM', 'DIS', 'TAX', 'INDUS','MEDV']]
bostonHouse_df.head()

      RM     DIS  TAX  INDUS  MEDV
0  6.575  4.0900  296   2.31  24.0
1  6.421  4.9671  242   7.07  21.6
2  7.185  4.9671  242   7.07  34.7
3  6.998  6.0622  222   2.18  33.4
4  7.147  6.0622  222   2.18  36.2

In [117]:
X=bostonHouse_df[[ 'RM','DIS', 'TAX', 'INDUS']]

from statsmodels.stats.outliers_influence import variance_inflation_factor
#calculating the VIF for each attributes
vif = pd.Series([variance_inflation_factor(X.values,idx) 
           for idx in range(X.shape[1])],
          index=X.columns)
print(vif)

RM       16.747965
DIS       6.880607
TAX      13.861510
INDUS     9.598374
dtype: float64

### Normalizing- Encoding categorical data

In [118]:
bostonHouse_df.columns.drop(['RM','TAX'])

Index(['DIS', 'INDUS', 'MEDV'], dtype='object')

In [119]:
# encoding categorical values

cat_features = ["DIS","INDUS"]
bostonHouse_df = pd.get_dummies(bostonHouse_df,columns=cat_features)
print(bostonHouse_df.columns)

Index(['RM', 'TAX', 'MEDV', 'DIS_1.1296', 'DIS_1.137', 'DIS_1.1691',
       'DIS_1.1742', 'DIS_1.1781', 'DIS_1.2024', 'DIS_1.2852',
       ...
       'INDUS_11.93', 'INDUS_12.83', 'INDUS_13.89', 'INDUS_13.92',
       'INDUS_15.04', 'INDUS_18.1', 'INDUS_19.58', 'INDUS_21.89',
       'INDUS_25.65', 'INDUS_27.74'],
      dtype='object', length=491)

### Normalizing Continuous DataSet

In [120]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler().fit(bostonHouse_df[['MEDV']])
bostonHouseData_Normalized=scaler.transform(bostonHouse_df[['MEDV']])
bostonHouseData_Normalized

array([[ 0.15968566],
       [-0.10152429],
       [ 1.32424667],
       [ 1.18275795],
       [ 1.48750288],
       [ 0.6712218 ],
       [ 0.03996443],
       [ 0.49708184],
       [-0.65659542],
       [-0.39538548],
       [-0.81985164],
       [-0.39538548],
       [-0.09064054],
       [-0.23212926],
       [-0.47157171],
       [-0.286548  ],
       [ 0.06173193],
       [-0.54775795],
       [-0.25389676],
       [-0.47157171],
       [-0.97222411],
       [-0.31919924],
       [-0.79808414],
       [-0.87427038],
       [-0.75454915],
       [-0.93957286],
       [-0.64571167],
       [-0.84161913],
       [-0.44980422],
       [-0.16682677],
       [-1.07017784],
       [-0.87427038],
       [-1.0157591 ],
       [-1.02664285],
       [-0.98310786],
       [-0.39538548],
       [-0.27566425],
       [-0.16682677],
       [ 0.23587189],
       [ 0.89978051],
       [ 1.34601416],
       [ 0.4426631 ],
       [ 0.30117438],
       [ 0.23587189],
       [-0.14505928],
       [-0.35185049],
       [-0.27566425],
       [-0.64571167],
       [-0.88515413],
       [-0.34096674],
       [-0.30831549],
       [-0.22124551],
       [ 0.26852314],
       [ 0.09438317],
       [-0.39538548],
       [ 1.4004329 ],
       [ 0.23587189],
       [ 0.98685049],
       [ 0.08349942],
       [-0.31919924],
       [-0.41715297],
       [-0.71101416],
       [-0.0362218 ],
       [ 0.26852314],
       [ 1.13922296],
       [ 0.10526692],
       [-0.34096674],
       [-0.0579893 ],
       [-0.55864169],
       [-0.17771052],
       [ 0.18145315],
       [-0.09064054],
       [ 0.02908069],
       [ 0.09438317],
       [ 0.17056941],
       [-0.12329178],
       [-0.27566425],
       [-0.18859427],
       [-0.14505928],
       [-0.24301301],
       [ 0.59503557],
       [ 0.14880191],
       [ 0.24675564],
       [ 0.03996443],
       [ 0.14880191],
       [ 0.4426631 ],
       [-0.00357056],
       [-0.0362218 ],
       [ 0.11615067],
       [ 0.6712218 ],
       [ 0.00731319],
       [-0.0579893 ],
       [ 0.03996443],
       [ 0.26852314],
       [-0.21036176],
       [ 0.63857056],
       [-0.12329178],
       [ 1.75959658],
       [ 2.31466771],
       [ 1.16099045],
       [ 0.54061683],
       [ 0.43177935],
       [-0.42803672],
       [-0.35185049],
       [-0.2647805 ],
       [-0.33008299],
       [-0.33008299],
       [-0.23212926],
       [-0.29743175],
       [-0.34096674],
       [-0.09064054],
       [ 0.02908069],
       [-0.40626922],
       [-0.41715297],
       [-0.43892047],
       [-0.46068796],
       [-0.14505928],
       [-0.36273423],
       [-0.23212926],
       [-0.35185049],
       [-0.0579893 ],
       [-0.24301301],
       [-0.22124551],
       [-0.56952544],
       [-0.40626922],
       [-0.12329178],
       [-0.7436654 ],
       [-0.68924667],
       [-0.49333921],
       [-0.89603787],
       [-0.36273423],
       [-0.31919924],
       [ 0.05084818],
       [-0.44980422],
       [-0.75454915],
       [-0.48245546],
       [-0.55864169],
       [-0.59129294],
       [-1.00487535],
       [-0.5151067 ],
       [-0.92868912],
       [-0.88515413],
       [-0.9939916 ],
       [-0.75454915],
       [-1.16813157],
       [-0.95045661],
       [-0.75454915],
       [-0.86338663],
       [-0.5151067 ],
       [-0.77631665],
       [-0.11240804],
       [-0.31919924],
       [-0.7872004 ],
       [-0.34096674],
       [-0.60217668],
       [-0.75454915],
       [-1.02664285],
       [ 2.04257402],
       [ 0.1923369 ],
       [ 0.08349942],
       [ 0.48619809],
       [ 2.98946007],
       [ 2.98946007],
       [ 2.98946007],
       [ 0.01819694],
       [ 0.26852314],
       [ 2.98946007],
       [ 0.13791816],
       [ 0.13791816],
       [-0.02533805],
       [-0.55864169],
       [-0.37361798],
       [ 0.06173193],
       [ 0.11615067],
       [ 0.00731319],
       [ 0.74740804],
       [ 0.07261568],
       [ 0.22498815],
       [ 0.80182678],
       [ 1.59634036],
       [ 1.8793178 ],
       [ 1.48750288],
       [ 1.6725266 ],
       [ 1.08480422],
       [ 0.4208956 ],
       [ 0.76917553],
       [ 2.98946007],
       [ 1.03038548],
       [ 0.79094303],
       [ 1.34601416],
       [ 1.57457287],
       [ 0.86712926],
       [ 1.50927038],
       [ 0.93243175],
       [ 0.71475679],
       [ 2.98946007],
       [ 1.1718742 ],
       [ 0.84536177],
       [ 1.31336292],
       [ 1.34601416],
       [ 1.12833921],
       [ 0.17056941],
       [ 2.1514115 ],
       [ 2.82620386],
       [ 2.98946007],
       [ 0.00731319],
       [ 0.20322065],
       [-0.00357056],
       [ 0.20322065],
       [-0.27566425],
       [-0.09064054],
       [-0.35185049],
       [-0.01445431],
       [ 0.60591932],
       [ 0.12703442],
       [ 0.26852314],
       [ 0.08349942],
       [ 0.6712218 ],
       [-0.11240804],
       [ 0.05084818],
       [ 0.45354685],
       [-0.09064054],
       [ 0.54061683],
       [ 0.82359427],
       [ 2.42350519],
       [ 2.98946007],
       [ 1.63987535],
       [ 0.98685049],
       [ 2.6302964 ],
       [ 0.97596674],
       [ 0.1923369 ],
       [ 0.99773424],
       [ 2.08610901],
       [ 2.80443636],
       [ 0.70387305],
       [ 0.15968566],
       [ 0.27940688],
       [ 0.97596674],
       [ 0.12703442],
       [ 0.08349942],
       [-0.0579893 ],
       [-0.2647805 ],
       [-0.0362218 ],
       [ 0.12703442],
       [-0.5368742 ],
       [-0.43892047],
       [ 0.1923369 ],
       [-0.22124551],
       [ 0.2141044 ],
       [ 0.39912811],
       [ 0.20322065],
       [ 0.24675564],
       [ 0.76917553],
       [ 2.20583024],
       [-0.06887304],
       [-0.17771052],
       [ 2.33643521],
       [ 2.98946007],
       [ 1.46573539],
       [ 0.82359427],
       [ 1.22629294],
       [ 2.23848148],
       [ 2.8588551 ],
       [ 0.921548  ],
       [ 1.52015413],
       [ 0.02908069],
       [ 0.88889676],
       [ 2.98946007],
       [ 2.28201647],
       [-0.19947802],
       [-0.15594303],
       [ 0.29029063],
       [ 0.20322065],
       [ 1.37866541],
       [ 1.07392047],
       [ 1.03038548],
       [ 1.16099045],
       [ 1.1501067 ],
       [ 0.71475679],
       [ 1.36778166],
       [ 2.48880768],
       [ 1.4004329 ],
       [ 2.55411016],
       [ 2.98946007],
       [ 1.05215297],
       [-0.0579893 ],
       [-0.2647805 ],
       [ 0.07261568],
       [-0.02533805],
       [ 0.24675564],
       [ 0.64945431],
       [ 1.60722411],
       [ 0.58415182],
       [ 0.14880191],
       [-0.09064054],
       [ 0.66033806],
       [ 0.49708184],
       [-0.24301301],
       [-0.00357056],
       [ 0.70387305],
       [ 0.24675564],
       [-0.0579893 ],
       [ 0.4208956 ],
       [ 1.1501067 ],
       [ 1.47661914],
       [ 0.63857056],
       [ 1.18275795],
       [ 0.61680306],
       [ 0.02908069],
       [-0.24301301],
       [-0.70013041],
       [-0.04710555],
       [-0.34096674],
       [-0.10152429],
       [ 0.13791816],
       [-0.68924667],
       [-0.5151067 ],
       [-0.29743175],
       [ 0.06173193],
       [-0.16682677],
       [ 0.13791816],
       [ 0.06173193],
       [-0.23212926],
       [-0.43892047],
       [ 0.26852314],
       [ 0.22498815],
       [ 0.05084818],
       [-0.0362218 ],
       [-0.35185049],
       [ 0.00731319],
       [-0.29743175],
       [-0.59129294],
       [-0.34096674],
       [-0.0362218 ],
       [-0.19947802],
       [-0.15594303],
       [-0.33008299],
       [-0.43892047],
       [-0.21036176],
       [-0.38450173],
       [-0.41715297],
       [ 1.10657171],
       [-0.65659542],
       [ 0.14880191],
       [ 0.9433155 ],
       [-0.54775795],
       [-0.58040919],
       [ 0.06173193],
       [ 0.2141044 ],
       [ 0.4426631 ],
       [ 0.03996443],
       [ 0.17056941],
       [-0.42803672],
       [ 0.82359427],
       [-0.47157171],
       [-0.21036176],
       [-0.5151067 ],
       [-0.09064054],
       [ 0.01819694],
       [ 0.00731319],
       [ 0.26852314],
       [-0.286548  ],
       [-0.18859427],
       [-0.62394418],
       [-0.06887304],
       [ 0.54061683],
       [-0.06887304],
       [ 0.06173193],
       [ 2.98946007],
       [ 2.98946007],
       [ 2.98946007],
       [ 2.98946007],
       [ 2.98946007],
       [-0.95045661],
       [-0.95045661],
       [-0.81985164],
       [-0.93957286],
       [-1.00487535],
       [-1.02664285],
       [-1.34227153],
       [-1.32050404],
       [-1.2660853 ],
       [-1.22255031],
       [-1.11371283],
       [-1.494644  ],
       [-1.66878396],
       [-1.30962029],
       [-1.64701647],
       [-1.34227153],
       [-1.20078281],
       [-0.80896789],
       [ 0.07261568],
       [-1.39669027],
       [-0.95045661],
       [-1.07017784],
       [-1.02664285],
       [-1.09194533],
       [-1.52729524],
       [-1.90822641],
       [-1.76673769],
       [-1.84292393],
       [-1.66878396],
       [-1.13548032],
       [-1.54906274],
       [-1.52729524],
       [-1.90822641],
       [-1.15724782],
       [ 0.58415182],
       [-0.58040919],
       [ 0.54061683],
       [-0.81985164],
       [-0.58040919],
       [-0.50422295],
       [-0.67836292],
       [-1.69055146],
       [-1.66878396],
       [-1.63613272],
       [-1.32050404],
       [-1.494644  ],
       [-1.53817899],
       [-0.63482793],
       [-0.90692162],
       [-0.18859427],
       [-0.9939916 ],
       [-1.17901531],
       [-1.54906274],
       [-1.34227153],
       [-1.2660853 ],
       [-1.25520155],
       [-1.41845777],
       [-0.87427038],
       [-0.91780537],
       [-0.70013041],
       [-0.89603787],
       [-1.17901531],
       [-0.9939916 ],
       [-1.40757402],
       [-1.50552775],
       [-1.53817899],
       [-1.05929409],
       [-1.30962029],
       [-0.59129294],
       [-0.44980422],
       [-0.77631665],
       [-1.27696904],
       [-1.16813157],
       [-0.83073539],
       [-1.08106158],
       [-0.91780537],
       [-1.03752659],
       [-0.9939916 ],
       [-0.79808414],
       [-0.70013041],
       [-0.5151067 ],
       [-0.83073539],
       [-0.91780537],
       [-1.07017784],
       [-0.98310786],
       [-0.83073539],
       [-0.27566425],
       [-0.66747917],
       [-0.52599045],
       [-0.33008299],
       [-0.25389676],
       [-0.12329178],
       [-0.286548  ],
       [-0.38450173],
       [-0.37361798],
       [-0.37361798],
       [-0.2647805 ],
       [-0.286548  ],
       [-0.31919924],
       [ 0.07261568],
       [ 0.79094303],
       [-0.95045661],
       [-1.00487535],
       [-0.63482793],
       [-1.14636407],
       [-0.86338663],
       [-0.12329178],
       [ 0.05084818],
       [ 0.12703442],
       [ 0.26852314],
       [-0.07975679],
       [-0.21036176],
       [-0.14505928],
       [-0.37361798],
       [-0.21036176],
       [-0.79808414],
       [-1.69055146],
       [-1.57083023],
       [-0.97222411],
       [-0.2647805 ],
       [-0.07975679],
       [ 0.2141044 ],
       [ 0.06173193],
       [-0.30831549],
       [-0.46068796],
       [-0.14505928],
       [-0.54775795],
       [-0.62394418],
       [-0.01445431],
       [-0.21036176],
       [ 0.14880191],
       [-0.0579893 ],
       [-1.15724782]])

#### Replacing the numerical columns with normalized values

In [121]:
#updating the numerical(normalized) data into the dataframe

bostonHouseNormalized_df=pd.DataFrame(bostonHouseData_Normalized, columns=['MEDV'])
bostonHouseNormalized_df=bostonHouseNormalized_df.join(bostonHouse_df[bostonHouse_df.columns.drop(['MEDV'])])

In [122]:
bostonHouseNormalized_df.head()

,MEDV,RM,TAX,DIS_1.1296,DIS_1.137,DIS_1.1691,DIS_1.1742,DIS_1.1781,DIS_1.2024,DIS_1.2852,...,INDUS_11.93,INDUS_12.83,INDUS_13.89,INDUS_13.92,INDUS_15.04,INDUS_18.1,INDUS_19.58,INDUS_21.89,INDUS_25.65,INDUS_27.74
0,0.159686,6.575,296,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,-0.101524,6.421,242,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1.324247,7.185,242,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1.182758,6.998,222,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1.487503,7.147,222,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

#### Selecting features and target

In [123]:
#bostonHouseNormalized_df.columns.drop(['RM'])

In [124]:
Y=bostonHouseNormalized_df['MEDV']
X=bostonHouseNormalized_df[bostonHouseNormalized_df.columns.drop(['MEDV'])]
print(X.shape)

(506, 490)

### Spillting into train & test data

In [125]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3, random_state=100)
X_train.shape , X_test.shape

((354, 490), (152, 490))

In [126]:
#importing required module to build the model
from sklearn.linear_model import LinearRegression

#building and training the model
model = LinearRegression()
model.fit(X_train,Y_train)

#Evaluating the model on the train and test data for R-Squared score 
train_score=model.score(X_train,Y_train)
test_score=model.score(X_test,Y_test)

print('Train Score (R-Squared): ',train_score)
print('Test Score (R-Squared)',test_score)

Train Score (R-Squared):  0.9870365752818168
Test Score (R-Squared) -3.0097955005301584e+16

In [127]:
from sklearn.metrics import mean_squared_error

#root mean square error (RMSE) calculation for train data
train_predictions = model.predict(X_train)
train_RMSE=mean_squared_error(Y_train,train_predictions)**0.5

#root mean square error (RMSE) calculation for test data
test_predictions = model.predict(X_test)
test_RMSE=mean_squared_error(Y_test,test_predictions)**0.5

print('Train RMSE : ',train_RMSE)
print('Test RMSE : ',test_RMSE)

Train RMSE :  0.10885282002626638
Test RMSE :  190028799.33888912